### ISSUE TITLE
FAIL: test_job_request_delete randomly

### ISSUE THREAD

**Issue by samueloph** [zeroSteiner/smoke-zephyr#4]
Hello, we detected on Debian that test_job_request_delete sometimes fails, I managed to catch that on Python 2.7, 3.6 and 3.7.

It was reported on our bug tracking system[0], and you can see more info and part of the failed build log there.

By trying to replicate on my machine, I get fails about 20% of the time, always on the same test job.

Do you have any idea on what is the problem here? Are you able to replicate on your machine?

Thanks,

[0]https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=906147

**Comment by zeroSteiner** [comment]
Yes, I've definitely seen this issue before. I've briefly looked into it in the past but haven't gotten a formal solution in place yet. I'll take another look though and see what I can do.

**Comment by samueloph** [comment]
@zeroSteiner what about the impact of this? Do you know if it's just a problem with the test or there's something wrong with the application (in a way that one can say it may be broken)?

Iff it's a problem with the test logic, may I suggest you to remove it on the next release?*

The package will only be able to hit testing and Ubuntu (and Kali to start syncing from Debian) after i close that bug.

*It's important to be sure that the problem is on the test itself and not on the application.

Thanks for your attention

**Comment by zeroSteiner** [comment]
I'm pretty sure it's only in the test case but I can't say for sure. I'll be able to look into it in the next few days.

**Comment by zeroSteiner** [comment]
Just wanted to give a quick update and let you know that I'm actively working on this. Thanks for your patience.

**Comment by zeroSteiner** [comment]
So I'm pretty sure this is a synchronization issue in the API. The particular test in question `job_request_delete` is the one in which the job requests that it be deleted, meaning that it has to be executed. Now the manager runs at approximately a second granularity, so when the job function slept for a second I'm thinking that the manager didn't have enough time to sleep and execute the job before processing the delete request before the test case checked.

I addressed this in commit 37b0e5c85541cb2b1cbe881fe487b108aeba13bc, which only modifies the test case. I ran it 20 times on both Python 2.7 and 3.6 with passes on all 40. If you want to give this a test and verify it, I'll get it in a new release.

**Comment by samueloph** [comment]
@zeroSteiner that commit fixed the problem for me, I'm uploading 1.3.3 with that commit to Debian unstable right now.

If the problem starts appearing again, our CI tools should detect them and I can report it to you again.

Thanks a lot for your work.

**Comment by zeroSteiner** [comment]
Excellent, I'm going to close this out then.

**Comment by samueloph** [comment]
@zeroSteiner The problem showed up again, the details are on this bugreport on Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=925208

Could you reopen this bug? I mean, if applicable.

For Debian I'll see if I can disable all of the tests so we can have the package on Buster.

Thanks

**Comment by zeroSteiner** [comment]
I finally figured out the underlying issue here. Unfortunately it looks like I was previously mistaken in thinking it was just the unit test. The `JobManager.stop` method was holding onto the `JobManager._job_lock` while waiting on the thread to exit (as done with `Thread.join`). However, the thread routine must acquire the lock before it begins it's iteration logic, the first part of which determines if it should has been instructed to stop. This caused a deadlock and timing issues.

In trying to reproduce this on a system with a single CPU, the unittests are reliably running smoothly now. This patch is included in commit a6d2498aeacc72ee52e7806f783a4d83d537ffb2 which in turn is included in version 1.4.1 that I just pushed up.

**Comment by samueloph** [comment]
@zeroSteiner thank you very much for the attention and the quick fix, now, if I understood correctly, there was a problem with smoke-zephyr itself and not its tests, right?

I just uploaded 1.4.1 to Debian unstable.

I will ask the Debian bug reporter to try to replicate the bug with 1.4.1.

**Comment by zeroSteiner** [comment]
Yeah, that's correct it was a problem with smoke-zephyr itself and it's use
of locks for synchronization.

**Comment by samueloph** [comment]
The submitter of the bug report on Debian confirmed that 1.4.1 fixes the problem for him, I will close the issue.

Thanks for your work @zeroSteiner
