### ISSUE TITLE
Failing test_get_ip_list with python 3.9

### ISSUE THREAD

**Issue by samueloph** [zeroSteiner/smoke-zephyr#8]
Hello, this is coming from a Debian bugreport:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973222

The test `test_get_ip_list` is failing with python 3.9, tested both on latest release and on the master branch:
```
======================================================================
FAIL: test_get_ip_list (utilities.UtilitiesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/samueloph/packaging/upstream/smoke-zephyr/tests/utilities.py", line 119, in test_get_ip_list
    self.assertEquals(returned_ip_list, ip_list, msg=("get_ip_list({!r}, mask={!r}) != {!r}".format(ip_network, mask, ip_list)))
AssertionError: Lists differ: ['192.168.1.0'] != []

First list contains 1 additional elements.
First extra element 0:
'192.168.1.0'

- ['192.168.1.0']
+ [] : get_ip_list('192.168.1.0/32', mask=None) != []

----------------------------------------------------------------------
Ran 27 tests in 14.027s

FAILED (failures=1)
```

The test is running fine with python 3.8.

Thanks,

**Comment by zeroSteiner** [comment]
Thanks for the report, I'll take a look.

**Comment by zeroSteiner** [comment]
Python seems to have changed how `ipaddress.ip_network` behaves with a netmask of 32 for IPv4 networks.

Python 3.8:
```
>>> [host.__str__() for host in ipaddress.ip_network('192.168.159.0/32').hosts()]
[]
```

Python 3.9:
```
>>> [host.__str__() for host in ipaddress.ip_network('192.168.159.0/32').hosts()]
['192.168.159.0']
```

I don't see anything in the [`ipaddress`](https://docs.python.org/3/library/ipaddress.html) documentation that mentions a change in v3.9 that could be related to this. I'll likely have to handle this as an edge case.

**Comment by zeroSteiner** [comment]
Fixed in commit ece91edefa7de9534068cb7e32af684141511789. I'm also using GitHub actions now for CI, with the unit tests running for version 3.4-3.9.

The fix isn't super clean because of the edge case but it ensures that callers have consistent behavior across Python versions.

**Comment by zeroSteiner** [comment]
And now v2.0.1 has been [published](https://pypi.org/project/smoke-zephyr/2.0.1/) to PyPi. You should be able to pull that down to fix your tests.

Thanks again for reporting this to me. Let me know if you have any other issues.

**Comment by samueloph** [comment]
Thank you!
I uploaded the latest release to Debian.

I have received a deprecation notice regarding usage of gvfs-open, I'm gonna open another issue to track that.
